"""Render a review as an MDPI-style Reviewer Report (.docx).

Targets the MDPI Review Report Form layout (Energies / Electronics / Applied
Sciences share it): a quality-evaluation grid (High/Average/Low/Not applicable),
a set of Yes / Can be improved / Must be improved questions, an overall
recommendation, and free-text "Comments and Suggestions for Authors".

Input is the dict form of a CrossJournalReport (i.e. the ``*__cross.json`` the
CLI writes) so it can be produced after the fact without re-running the LLMs.
"""
from __future__ import annotations

from pathlib import Path

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

_REC_LABEL = {
    "accept": "Accept in present form",
    "minor_revision": "Accept after minor revision",
    "major_revision": "Reconsider after major revision",
    "reject": "Reject",
}

_REC_LABEL_ZH = {
    "accept": "接受（无需修改）",
    "minor_revision": "小修后接受",
    "major_revision": "大修后重审",
    "reject": "拒稿",
}

# UI strings per language (labels only; body text is translated separately)
_L = {
    "en": {
        "report_title": "{j} (MDPI) — Reviewer Report",
        "subtitle": "Pre-submission self-check generated by a multi-agent review system; "
                    "for author use only — not an official peer review.",
        "f_field": "Field", "f_value": "Value",
        "m_manuscript": "Manuscript", "m_journal": "Target Journal",
        "m_rec": "Recommendation", "m_rri": "Acceptance-risk index (RRI)",
        "rri_fmt": "{rri}/100 ({tier}) — predicted: {pred}",
        "s1": "1. Quality Evaluation", "eval": "Evaluation", "rating": "Rating",
        "s2": "2. Review Questions", "question": "Question", "assessment": "Assessment",
        "s3": "3. Comments and Suggestions for Authors",
        "summary": "Summary", "strengths": "Strengths",
        "majors": "Major points", "minors": "Minor points",
        "evidence": "Evidence: ", "fix": "Suggested fix: ",
        "s4": "4. Journal-specific notes (Energies / MDPI)",
        "dims": ["Originality / Novelty", "Significance of Content", "Scientific Soundness",
                 "Interest to the Readers", "Quality of Presentation", "English Level",
                 "Overall Merit"],
        "rate_high": "High", "rate_avg": "Average", "rate_low": "Low", "rate_na": "Can't assess",
        "questions": [
            "Does the introduction provide sufficient background and include all relevant references?",
            "Are all the cited references recent and relevant to the research (incl. last 5 years)?",
            "Is the research design appropriate?",
            "Are the methods adequately described and reproducible?",
            "Are the results clearly presented?",
            "Are the conclusions supported by the results?",
        ],
        "q_yes": "Yes", "q_can": "Can be improved", "q_must": "Must be improved",
        "notes": [
            "MDPI is a DORA signatory and publishes scientifically sound negative / non-SOTA "
            "results; explicitly argue the value of the (partially negative) finding under the "
            "Interest-to-Readers / Overall-Merit lens.",
            "Citations should emphasise the last five years and avoid excessive self-citation.",
            "A Data Availability Statement and code/data deposition (e.g. Zenodo/GitHub with DOI) "
            "are expected; add them or justify their absence.",
            "Energies uses a tiered decision model (Accept / Minor / Major / Reject) — the issues "
            "above are addressable via major revision rather than outright rejection.",
        ],
    },
    "zh": {
        "report_title": "{j}（MDPI）— 审稿意见",
        "subtitle": "本意见由多智能体系统生成，供作者投稿前自检参考，非正式同行评审，最终判断须由人类负责。",
        "f_field": "项目", "f_value": "内容",
        "m_manuscript": "稿件", "m_journal": "目标期刊",
        "m_rec": "审稿推荐", "m_rri": "录用风险指数 (RRI)",
        "rri_fmt": "{rri}/100（{tier}）— 预测决策：{pred}",
        "s1": "一、质量评级", "eval": "评估维度", "rating": "评级",
        "s2": "二、审稿问题", "question": "问题", "assessment": "评定",
        "s3": "三、给作者的具体意见",
        "summary": "总体评价", "strengths": "优点",
        "majors": "主要问题（须修改）", "minors": "次要问题（建议改进）",
        "evidence": "证据：", "fix": "修改建议：",
        "s4": "四、期刊专项提示（Energies / MDPI）",
        "dims": ["原创性 / 创新性", "内容的重要性", "科学严谨性",
                 "对读者的价值/兴趣", "表述质量", "英语水平", "总体价值"],
        "rate_high": "高", "rate_avg": "中", "rate_low": "低", "rate_na": "无法评估",
        "questions": [
            "引言是否提供了充分背景并包含所有相关文献？",
            "所引文献是否新近且相关（含近 5 年）？",
            "研究设计是否恰当？",
            "方法描述是否充分、可复现？",
            "结果呈现是否清晰？",
            "结论是否被结果充分支撑？",
        ],
        "q_yes": "是", "q_can": "可改进", "q_must": "须改进",
        "notes": [
            "MDPI 为 DORA 签署方，发表科学上正确的负面/非-SOTA 结果；请在「对读者价值/总体价值」视角下"
            "明确论证该（部分负面）结论的价值。",
            "引用应以近 5 年为主，避免过度自引。",
            "需提供数据可用性声明（Data Availability Statement）及代码/数据存档（如带 DOI 的 Zenodo/GitHub），"
            "或说明不提供的合理原因。",
            "Energies 为分档决策（接受/小修/大修/拒稿）——上述问题可通过大修解决，而非直接拒稿。",
        ],
    },
}


def _rating(score):
    """Map a 1–10 rubric score to a canonical rating code."""
    if score is None:
        return "na"
    if score >= 7:
        return "high"
    if score >= 5.5:
        return "avg"
    return "low"


def _dim_score(reviews: dict, key: str):
    for r in reviews:
        if r["dimension"] == key:
            return r.get("score")
    return None


def _avg(*vals):
    nums = [v for v in vals if v is not None]
    return round(sum(nums) / len(nums), 2) if nums else None


def _question_verdict(score, has_fatal):
    """Canonical code: must / can / yes from a dimension's health."""
    if has_fatal or (score is not None and score < 5):
        return "must"
    if score is not None and score < 7:
        return "can"
    return "yes"


def _all_findings(reviews):
    out = []
    for r in reviews:
        for f in r.get("findings", []):
            out.append(f)
    return out


def _dim_has_fatal(reviews, key, thresh=3):
    for r in reviews:
        if r["dimension"] == key:
            return any(f.get("severity", 0) >= thresh for f in r.get("findings", []))
    return False


# ---- styling helpers ----
def _h(doc, text, size=13):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(size)
    run.font.color.rgb = RGBColor(0x1F, 0x3B, 0x73)
    return p


def _kv_table(doc, rows, col0="Evaluation", col1="Rating"):
    t = doc.add_table(rows=1, cols=2)
    t.style = "Light Grid Accent 1"
    hdr = t.rows[0].cells
    hdr[0].paragraphs[0].add_run(col0).bold = True
    hdr[1].paragraphs[0].add_run(col1).bold = True
    for k, v in rows:
        c = t.add_row().cells
        c[0].text = k
        c[1].text = str(v)
    return t


def render_mdpi_review_docx(data: dict, venue: str, out_path: str | Path,
                            manuscript_title: str = "", lang: str = "en") -> Path:
    L = _L.get(lang, _L["en"])
    rate_map = {"high": L["rate_high"], "avg": L["rate_avg"],
                "low": L["rate_low"], "na": L["rate_na"]}
    q_map = {"yes": L["q_yes"], "can": L["q_can"], "must": L["q_must"]}
    rec_label = _REC_LABEL_ZH if lang == "zh" else _REC_LABEL

    pred_zh = {
        "accept": "接受", "accept_or_minor": "接受/小修", "minor_or_major": "小修/大修",
        "major_revision": "大修", "major_to_reject": "大修→拒稿边缘",
        "reject": "拒稿", "borderline-reject": "边缘偏拒",
    }

    reviews = data.get("dimension_reviews", [])
    meta = (data.get("meta_reviews", {}) or {}).get(venue, {}) or {}
    risk = next((r for r in data.get("risks", []) if r["venue"] == venue), {})
    rec = meta.get("recommendation") or "major_revision"

    venue_name = {"mdpi_energies": "Energies", "mdpi_electronics": "Electronics",
                  "mdpi_applied_sciences": "Applied Sciences",
                  "ieee_access": "IEEE Access"}.get(venue, venue)
    is_mdpi = venue.startswith("mdpi")

    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Microsoft YaHei" if lang == "zh" else "Calibri"
    style.font.size = Pt(10.5)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_txt = (L["report_title"].format(j=venue_name) if is_mdpi
                 else (f"{venue_name} — 审稿意见" if lang == "zh"
                       else f"{venue_name} — Reviewer Report"))
    r = title.add_run(title_txt)
    r.bold = True
    r.font.size = Pt(16)

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.add_run(L["subtitle"]).italic = True

    doc.add_paragraph()
    pred_raw = risk.get("predicted_decision", "")
    pred = pred_zh.get(pred_raw, pred_raw) if lang == "zh" else pred_raw
    rri_text = L["rri_fmt"].format(rri=risk.get("rri", "?"), tier=risk.get("tier", ""),
                                   pred=pred)
    meta_rows = [
        (L["m_manuscript"], manuscript_title or data.get("paper_id", "")),
        (L["m_journal"], f"{venue_name} (MDPI)" if is_mdpi else venue_name),
        (L["m_rec"], rec_label.get(rec, rec)),
        (L["m_rri"], rri_text),
    ]
    _kv_table(doc, meta_rows, col0=L["f_field"], col1=L["f_value"])

    # --- quality evaluation grid (MDPI 6+ dimensions) ---
    doc.add_paragraph()
    _h(doc, L["s1"])
    nov = _dim_score(reviews, "novelty")
    snd = _dim_score(reviews, "soundness")
    exp = _dim_score(reviews, "experiments")
    rep = _dim_score(reviews, "reproducibility")
    clr = _dim_score(reviews, "clarity")
    overall = meta.get("overall_score")
    # major_revision implies salvageable → keep Overall Merit at least Average
    overall_code = _rating(overall)
    if rec in ("major_revision", "minor_revision") and overall_code == "low":
        overall_code = "avg"
    codes = [_rating(nov), _rating(_avg(nov, clr)), _rating(_avg(snd, exp, rep)),
             _rating(clr), _rating(clr), "avg", overall_code]
    grid = [(L["dims"][i], rate_map[c]) for i, c in enumerate(codes)]
    _kv_table(doc, grid, col0=L["eval"], col1=L["rating"])

    # --- structured questions ---
    doc.add_paragraph()
    _h(doc, L["s2"])
    rw = _dim_score(reviews, "related_work")
    verdicts = [
        _question_verdict(rw, _dim_has_fatal(reviews, "related_work")),
        _question_verdict(rw, _dim_has_fatal(reviews, "related_work")),
        _question_verdict(_avg(snd, exp), _dim_has_fatal(reviews, "experiments")),
        _question_verdict(rep, _dim_has_fatal(reviews, "reproducibility")),
        _question_verdict(clr, _dim_has_fatal(reviews, "clarity")),
        _question_verdict(_avg(nov, snd), _dim_has_fatal(reviews, "novelty")),
    ]
    questions = [(L["questions"][i], q_map[v]) for i, v in enumerate(verdicts)]
    _kv_table(doc, questions, col0=L["question"], col1=L["assessment"])

    # --- comments to authors ---
    doc.add_paragraph()
    _h(doc, L["s3"])

    if meta.get("summary"):
        doc.add_paragraph().add_run(L["summary"]).bold = True
        doc.add_paragraph(meta["summary"])

    if meta.get("key_strengths"):
        doc.add_paragraph().add_run(L["strengths"]).bold = True
        for s in meta["key_strengths"]:
            doc.add_paragraph(s, style="List Bullet")

    findings = _all_findings(reviews)
    majors = [f for f in findings if f.get("severity", 0) >= 3]
    minors = [f for f in findings if f.get("severity", 0) == 2]
    majors.sort(key=lambda f: f.get("severity", 0), reverse=True)

    if majors:
        doc.add_paragraph().add_run(L["majors"]).bold = True
        for f in majors:
            p = doc.add_paragraph(style="List Number")
            p.add_run(f.get("issue", "")).bold = True
            if f.get("reviewer_voice"):
                doc.add_paragraph(f.get("reviewer_voice"))
            if f.get("evidence"):
                ev = doc.add_paragraph()
                ev.add_run(L["evidence"]).italic = True
                ev.add_run(f.get("evidence"))
            if f.get("fix_suggestion"):
                fx = doc.add_paragraph()
                fx.add_run(L["fix"]).italic = True
                fx.add_run(f.get("fix_suggestion"))

    if minors:
        doc.add_paragraph().add_run(L["minors"]).bold = True
        for f in minors:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(f.get("issue", ""))
            if f.get("fix_suggestion"):
                p.add_run(" — " + f.get("fix_suggestion")).italic = True

    # venue-specific reminders
    doc.add_paragraph()
    if is_mdpi:
        _h(doc, L["s4"], size=11)
        notes = L["notes"]
    else:
        _h(doc, ("四、期刊专项提示（IEEE Access）" if lang == "zh"
                 else "4. Journal-specific notes (IEEE Access)"), size=11)
        notes = ([
            "IEEE Access 为二元 accept/reject 模型，无大修缓冲——'差一点'即拒。审稿意见虽可列'大修级'建议，"
            "但作者须在一轮内改到可录用水平。",
            "官方红线（任一即拒）：英语语法硬伤、技术致命错误/结论与数据矛盾、含撤稿文献、与既往发表无可辨识差异、明显超 scope。",
            "不要求高创新度，但必须 distinct from prior + 技术 sound + 证据充分支撑结论 + 与强基线公平对比 + 可复现。",
            "对负面/非-SOTA 结论：IEEE Access 可接受，前提是技术正确且 distinct；关键在证明'该负面结论是有效假设下的稳健结论'"
            "（多系统/多设置验证、排除伪负面），并明确其对领域的实用价值。",
        ] if lang == "zh" else [
            "IEEE Access is a binary accept/reject venue (no major-revision buffer).",
            "Red lines (any → reject): fatal grammar, fatal technical error/claims contradicting data, "
            "retracted refs, not distinct from prior work, out of scope.",
            "Novelty need not be high, but the work must be distinct, technically sound, evidence-backed, "
            "fairly compared to strong baselines, and reproducible.",
            "Negative/non-SOTA results are acceptable if technically correct and distinct; prove the negative "
            "conclusion is robust (multi-system/multi-setting, no false negative) and state its practical value.",
        ])
    for n in notes:
        doc.add_paragraph(n, style="List Bullet")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out_path))
    return out_path
